  - name: Copy letsencrypt unit
    copy:
      src: "{{ role_path }}/files/letsencrypt.service"
      dest: /etc/systemd/system/
    tags:
      - setup-letsencrypt

  - name: Enable letsencrypt service
    service: name=letsencrypt.service enabled=true state=started
    tags:
      - setup-letsencrypt
      - enable-letsencrypt

  - name: Restart letsencrypt service
    service: name=letsencrypt.service enabled=true state=restarted
    tags:
      - setup-letsencrypt
      - restart-letsencrypt