kind: RoleBinding
apiVersion: "rbac.authorization.k8s.io/v1beta1"
metadata:
  name: deployment-manager-binding
  namespace: staging
subjects:
- kind: Group 
  name: dev
  apiGroup: ""
- kind: User
  name: "some-user"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: staging-deployment-manager
  apiGroup: ""
