kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: monitoring
  namespace: kube-system
subjects:
- kind: User
  name: deployer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: monitoring
  apiGroup: ""
