kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prod-deploy
subjects:
- kind: User
  name: travis
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-deploy
  apiGroup: ""
