  kind: Role
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    namespace: default
    name:  prod-deploy
  rules:
  - apiGroups: ["", "", "apps", "extensions", "replicasets"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
