kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prod-full-access
  namespace: default
subjects:
- kind: User
  name: luis.bernardes
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: wesley.ramos
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: diego.mello
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-full-access
  apiGroup: ""
