---
- name: include apt-repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    update_cache: yes
    state: present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - setup-docker

- name: Upgrade all packages to the latest version
  apt:
    force_apt_get: true
    name: "*"
    state: latest

- name: Install Linux extra Headers
  apt:
    name: "linux-image-extra-{{ ansible_kernel}}"
    state: present
    force: yes
  become: true
  tags:
    - setup-docker


- name: Install Linux extra virtual
  apt:
    name: "linux-image-extra-virtual"
    state: present
    force: yes
  become: true
  tags:
    - setup-docker


- name: Install docker present
  apt:
    name: "docker-ce=17.09.1~ce-0~ubuntu"
    state: present
    force: yes
  become: true
  tags:
    - setup-docker

- name: Copy docker systemd unit
  copy:
    src: "{{ role_path }}/files/docker.service"
    dest: /etc/systemd/system/docker.service
  become: true
  tags:
    - setup-docker
    - setup-docker-service

- name: Copy swarm server-cert
  copy:
    src: "{{ role_path }}/files/certs/"
    dest: /data/.certs
  become: true
  tags:
    - setup-docker
    - setup-docker-service

- name: Enable Docker service
  service: name=docker.service enabled=true state=started
  become: true

- systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  tags:
    - setup-docker
    - setup-docker-service
    - restart-docker

- name: install dockerpy
  pip: name=docker-py version=1.9.0
  become: true
  tags:
    - setup-docker
    - setup-docker-service